# Default values for pihole.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

pihole:
  name: pihole

  replicaCount: 1
  restartPolicy: Always

  image:
    repository: pihole/pihole
    tag: v5.1.2
    pullPolicy: Always

  existingSecret:
  secrets:
    webPassword: changeMe

  config:
    virtualHost: 127.0.0.1
    tz: UTC
    dns1: 9.9.9.9
    dns2: 149.112.112.112
    dnsSec: 1

  service:
    type: ClusterIP
    http:
      port: 80
      targetPort: 80
      protocol: TCP
    dns:
      port: 53
      targetPort: 53
      protocol: TCP

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

dohProxy:
  name: doh-httpproxy

  enabled: false

  replicaCount: 1
  restartPolicy: Always

  image:
    repository: krewh/doh-httpproxy
    tag: 0.0.3
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
    protocol: TCP

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

nginx:
  name: nginx

  replicaCount: 1
  restartPolicy: Always

  image:
    repository: krewh/hardened-nginx
    tag: 1.1.3
    pullPolicy: Always

  config:
    adminAuthorizedIps: 0.0.0.0/0
    dnsOverTlsGateway:
      enabled: false
      proxyProtocol: false
      sslTermination: false
    dnsQueryLogging:
      enabled: false

  dotCertificate:
    create: false
    name: dot-certificate
    existingSecret:
    dnsNames: []
    issuer:
      name: letsencrypt-production
      kind: ClusterIssuer
      group: cert-manager.io

  service:
    type: ClusterIP
    https:
      port: 443
      targetPort: 443
      protocol: TCP
    dot:
      port: 853
      targetPort: 853
      protocol: TCP

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    #kubernetes.io/tls-acme: "true"

  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
