# Default values for pihole.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

deployments:
  pihole:
    image:
      repository: pihole/pihole
      tag: latest
      pullPolicy: Always
  dohHttpProxy:
    image:
      repository: krewh/doh-httpproxy
      tag: latest
      pullPolicy: Always

config:
  ServerIP: 127.0.0.1
  VIRTUAL_HOST: 127.0.0.1
  TZ: UTC
  DNS1: 9.9.9.9
  DNS2: 149.112.112.112

secrets:
  WEBPASSWORD: changeMe

services:
  http:
    type: ClusterIP
    port: 80
    targetPort: 80
    protocol: TCP
  doh:
    type: ClusterIP
    port: 8080
    targetPort: 8080
    protocol: TCP

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
  http:
    paths:
      - /
    hosts: []
    # - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  doh:
    paths:
      - /
    hosts: []
      # - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

restartPolicy: Always
