apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poh.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "poh.name" . }}
    helm.sh/chart: {{ include "poh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
{{- end }}
