{{- if .Values.dohProxy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.dohProxy.name }}
  labels:
{{ include "poh.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.dohProxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "poh.name" . }}-{{ .Values.dohProxy.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "poh.name" . }}-{{ .Values.dohProxy.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.dohProxy.name }}
          image: "{{ .Values.dohProxy.image.repository }}:{{ .Values.dohProxy.image.tag }}"
          imagePullPolicy: {{ .Values.dohProxy.image.pullPolicy }}
          env:
            - name: LISTEN_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RESOLVER_HOST
              value: {{ include "poh.fullname" . }}-{{ .Values.pihole.name }}.{{ .Release.Namespace }}.svc.cluster.local
          ports:
            - name: doh
              containerPort: {{ .Values.dohProxy.service.targetPort }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
          resources:
            {{- toYaml .Values.dohProxy.resources | nindent 12 }}
      restartPolicy: {{ .Values.dohProxy.restartPolicy }}
      {{- with .Values.dohProxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.dohProxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.dohProxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
