---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.nginx.name }}-streams
  labels:
{{ include "poh.labels" . | indent 4 }}
data:
  stream.conf: |
    {{- if .Values.nginx.config.dnsOverTlsGateway.enabled -}}
    # DNS upstream pool
    upstream dns {
        zone dns 64k;
        server 10.97.101.125:53;
    }

    # DoT server for decryption
    server {
        listen 853 ssl;
        proxy_pass dns;
        proxy_ssl_verify off;
    }
    {{- end -}}
