---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.nginx.name }}
  labels:
{{ include "poh.labels" . | indent 4 }}
data:
  default.conf: |
    server {
      listen 443 ssl http2;
      listen [::]:443 ssl http2;

      ssl on;

      ssl_certificate /etc/nginx/ssl/cert.pem;
      ssl_certificate_key /etc/nginx/ssl/key.pem;

      server_name _;

      set_real_ip_from 0.0.0.0/0;
      real_ip_header X-Forwarded-For;

      location / {
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://{{ include "poh.fullname" . }}-{{ .Values.poh.name }}:80;
      }

      location /dns-query {
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://{{ include "poh.fullname" . }}-{{ .Values.poh.name }}:8080;
      }
    }
