apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.nginx.name }}
  labels:
{{ include "poh.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "poh.name" . }}-{{ .Values.nginx.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "poh.name" . }}-{{ .Values.nginx.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        sitesConfigChecksum: {{ include (print .Template.BasePath "/nginx-configMap-sites.yaml") . | sha256sum | trunc 63 }}
        streamsConfigChecksum: {{ include (print .Template.BasePath "/nginx-configMap-streams.yaml") . | sha256sum | trunc 63 }}
    spec:
      restartPolicy: {{ .Values.nginx.restartPolicy }}
    {{- with .Values.nginx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.nginx.name }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.nginx.service.https.targetPort }}
              protocol: TCP
            {{- if .Values.nginx.config.dnsOverTlsGateway.enabled }}
            - name: dot
              containerPort: {{ .Values.nginx.service.dot.targetPort }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/sites
              name: nginx-sites
            - mountPath: /etc/nginx/conf.d/streams
              name: nginx-streams
            {{- if and .Values.nginx.config.dnsOverTlsGateway.enabled .Values.nginx.config.dnsOverTlsGateway.sslTermination }}
            - name: ssl-certificates
              mountPath: "/etc/nginx/ssl/dot"
              readOnly: true
            {{- end }}
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - configMap:
            name: {{ include "poh.fullname" . }}-{{ .Values.nginx.name }}-sites
          name: nginx-sites
        - configMap:
            name: {{ include "poh.fullname" . }}-{{ .Values.nginx.name }}-streams
          name: nginx-streams
        {{- if .Values.nginx.config.dnsOverTlsGateway.sslTermination }}
        - name: ssl-certificates
          secret:
            {{- if and .Values.nginx.config.dnsOverTlsGateway.enabled .Values.nginx.config.dnsOverTlsGateway.sslTermination .Values.nginx.dotCertificate.create }}
            secretName: {{ include "poh.fullname" . }}-{{ .Values.nginx.dotCertificate.name }}
            {{- else if and .Values.nginx.config.dnsOverTlsGateway.enabled .Values.nginx.config.dnsOverTlsGateway.sslTermination }}
            secretName: {{ .Values.nginx.dotCertificate.existingSecret }}
            {{- end }}
        {{- end }}
