---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.nginx.name }}-streams
  labels:
{{ include "poh.labels" . | indent 4 }}
data:
  stream.conf: |
    {{- if .Values.nginx.config.dnsOverTlsGateway.enabled -}}
    # DNS upstream pool
    upstream dns {
        zone dns 64k;
        server {{ include "poh.fullname" . }}-{{ .Values.pihole.name }}:{{ .Values.pihole.service.dns.port }};
    }

    # DoT server for decryption
    server {
        listen 853; # SSL termination is done on LB/Proxy side
        proxy_pass dns;
    }
    {{- end -}}
