---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.nginx.name }}-sites
  labels:
{{ include "poh.labels" . | indent 4 }}
data:
  default.conf: |
    server {
      listen 443 ssl http2;
      listen [::]:443 ssl http2;

      server_name _;

      set_real_ip_from 0.0.0.0/0;
      real_ip_header X-Forwarded-For;

      # Generic error page
      error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 425 426 428 429 431 451 500 501 502 503 504 505 506 507 508 510 511 /error.html;
      location = /error.html {
        ssi on;
        internal;
        auth_basic off;
        root /usr/share/nginx/html;
      }

      location / {
        allow {{ .Values.nginx.config.adminAuthorizedIps }};
        deny all;

        proxy_set_header Host $proxy_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://{{ include "poh.fullname" . }}-{{ .Values.pihole.name }}:{{ .Values.pihole.service.http.port }};
      }

      {{ if .Values.dohProxy.enabled }}
      location /dns-query {
        {{- if not .Values.nginx.config.dnsQueryLogging.enabled }}
        access_log off;
        {{- end }}

        proxy_set_header Host $proxy_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://{{ include "poh.fullname" . }}-{{ .Values.dohProxy.name }}:{{ .Values.dohProxy.service.port }};
      }
      {{ end }}
    }
