apiVersion: v1
kind: Service
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.nginx.name }}-https
  labels:
{{ include "poh.labels" . | indent 4 }}
spec:
  type: {{ .Values.nginx.service.https.type }}
  ports:
    - port: {{ .Values.nginx.service.https.port }}
      targetPort: {{ .Values.nginx.service.https.targetPort }}
      protocol: {{ .Values.nginx.service.https.protocol }}
      name: https
  selector:
    app.kubernetes.io/name: {{ include "poh.name" . }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
