---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "poh.fullname" . }}-pihole
  labels:
    app.kubernetes.io/name: {{ include "poh.name" . }}-pvc
    helm.sh/chart: {{ include "poh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
