{{- if not .Values.pihole.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.pihole.name }}
  labels:
{{ include "poh.labels" . | indent 4 }}
type: Opaque
data:
  webPassword: {{ .Values.pihole.secrets.webPassword | b64enc }}
{{- end }}
