apiVersion: v1
kind: Service
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.pihole.name }}
  labels:
{{ include "poh.labels" . | indent 4 }}
spec:
  type: {{ .Values.pihole.service.type }}
  ports:
    - port: {{ .Values.pihole.service.http.port }}
      targetPort: {{ .Values.pihole.service.http.targetPort }}
      protocol: {{ .Values.pihole.service.http.protocol }}
      name: http
    - port: {{ .Values.pihole.service.dns.port }}
      targetPort: {{ .Values.pihole.service.dns.targetPort }}
      protocol: {{ .Values.pihole.service.dns.protocol }}
      name: dns
  selector:
    app.kubernetes.io/name: {{ include "poh.name" . }}-{{ .Values.pihole.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
