apiVersion: v1
kind: Service
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.poh.name }}-pihole
  labels:
{{ include "poh.labels" . | indent 4 }}
spec:
  type: {{ .Values.poh.service.dns.type }}
  ports:
    - port: {{ .Values.poh.service.dns.port }}
      targetPort: {{ .Values.poh.service.dns.targetPort }}
      protocol: {{ .Values.poh.service.dns.protocol }}
      name: dns
  selector:
    app.kubernetes.io/name: {{ include "poh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
