---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.poh.pihole.name }}
  labels:
{{ include "poh.labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
