apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poh.fullname" . }}-{{ .Values.poh.name }}
  labels:
{{ include "poh.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.poh.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "poh.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "poh.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.poh.pihole.name }}
          image: "{{ .Values.poh.pihole.image.repository }}:{{ .Values.poh.pihole.image.tag }}"
          imagePullPolicy: {{ .Values.poh.pihole.image.pullPolicy }}
          env:
            - name: VIRTUAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "poh.fullname" . }}-{{ .Values.poh.name }}
                  key: VIRTUAL_HOST
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: {{ include "poh.fullname" . }}-{{ .Values.poh.name }}
                  key: TZ
            - name: DNS1
              valueFrom:
                configMapKeyRef:
                  name: {{ include "poh.fullname" . }}-{{ .Values.poh.name }}
                  key: DNS1
            - name: DNS2
              valueFrom:
                configMapKeyRef:
                  name: {{ include "poh.fullname" . }}-{{ .Values.poh.name }}
                  key: DNS2
            - name: DNSSEC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "poh.fullname" . }}-{{ .Values.poh.name }}
                  key: DNSSEC
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "poh.secretName" . }}
                  key: WEBPASSWORD
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          restartPolicy: {{ .Values.restartPolicy }}
          volumeMounts:
            - mountPath: /etc/pihole/
              name: pihole-storage
          resources:
            {{- toYaml .Values.poh.pihole.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-{{ .Values.poh.doh.name }}
          image: "{{ .Values.poh.doh.image.repository }}:{{ .Values.poh.doh.image.tag }}"
          imagePullPolicy: {{ .Values.poh.doh.image.pullPolicy }}
          env:
            - name: LISTEN_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RESOLVER
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: doh
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
          restartPolicy: {{ .Values.poh.restartPolicy }}
          resources:
            {{- toYaml .Values.poh.doh.resources | nindent 12 }}
      {{- with .Values.poh.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.poh.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.poh.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: pihole-storage
          persistentVolumeClaim:
            claimName: {{ include "poh.fullname" . }}-{{ .Values.poh.pihole.name }}
