apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poh.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "poh.name" . }}
    helm.sh/chart: {{ include "poh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
